version: '3'

services:
  db:
    image: sistema_db_utilizando_docker-db:latest
    environment:
      - POSTGRES_USER=mybank
      - POSTGRES_PASSWORD=mybank
      - POSTGRES_DB=mybank
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
